{
    "sourceFile": "src/hooks/useError.ts",
    "activeCommit": 0,
    "commits": [
        {
            "activePatchIndex": 4,
            "patches": [
                {
                    "date": 1740773771665,
                    "content": "Index: \n===================================================================\n--- \n+++ \n"
                },
                {
                    "date": 1740773785033,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -1,10 +1,2 @@\n-import { useContext } from 'react';\r\n-import { ErrorContext, type ErrorContextType } from '../contexts/ErrorContext';\r\n-\r\n-export const useError = (): ErrorContextType => {\r\n-  const context = useContext(ErrorContext);\r\n-  if (!context) {\r\n-    throw new Error('useError must be used within an ErrorProvider');\r\n-  }\r\n-  return context;\r\n-};\n\\ No newline at end of file\n+// Re-export the useError hook from the ErrorContext\r\n+export { useError } from '../contexts/ErrorContext';\n\\ No newline at end of file\n"
                },
                {
                    "date": 1740775190646,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -1,2 +1,10 @@\n-// Re-export the useError hook from the ErrorContext\r\n-export { useError } from '../contexts/ErrorContext';\n\\ No newline at end of file\n+import { useContext } from 'react';\r\n+import { ErrorContext, type ErrorContextType } from '../contexts/ErrorContext';\r\n+\r\n+export const useError = (): ErrorContextType => {\r\n+  const context = useContext(ErrorContext);\r\n+  if (!context) {\r\n+    throw new Error('useError must be used within an ErrorProvider');\r\n+  }\r\n+  return context;\r\n+};\n\\ No newline at end of file\n"
                },
                {
                    "date": 1740775203917,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -1,6 +1,6 @@\n import { useContext } from 'react';\r\n-import { ErrorContext, type ErrorContextType } from '../contexts/ErrorContext';\r\n+import { ErrorContext,  } from '../contexts/ErrorContext';\r\n \r\n export const useError = (): ErrorContextType => {\r\n   const context = useContext(ErrorContext);\r\n   if (!context) {\r\n"
                },
                {
                    "date": 1740775210193,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -1,6 +1,6 @@\n import { useContext } from 'react';\r\n-import { ErrorContext,  } from '../contexts/ErrorContext';\r\n+import { ErrorContext, type ErrorContextType } from '../contexts/ErrorContext';\r\n \r\n export const useError = (): ErrorContextType => {\r\n   const context = useContext(ErrorContext);\r\n   if (!context) {\r\n"
                }
            ],
            "date": 1740773771665,
            "name": "Commit-0",
            "content": "import { useContext } from 'react';\r\nimport { ErrorContext, type ErrorContextType } from '../contexts/ErrorContext';\r\n\r\nexport const useError = (): ErrorContextType => {\r\n  const context = useContext(ErrorContext);\r\n  if (!context) {\r\n    throw new Error('useError must be used within an ErrorProvider');\r\n  }\r\n  return context;\r\n};"
        }
    ]
}